using System.Collections.Generic;
using System.ComponentModel;
using System.Windows.Data;

namespace AssetCuaStudio;

// Lightweight live-switchable i18n (mirrors AudioCuaStudio's L). Bind static text via
// {Binding [key], Source={x:Static loc:L.I}}; switching language raises the indexer change so
// all bindings refresh in place.
public class L : INotifyPropertyChanged
{
    public static L I { get; } = new L();
    public event PropertyChangedEventHandler PropertyChanged;

    public static readonly (string code, string name)[] Languages =
    {
        ("en", "English"), ("ko", "한국어"), ("ja", "日本語"), ("zh-Hant", "繁體中文"),
    };

    public string Lang { get; private set; } = "en";
    public string this[string key] => T(key);

    public string T(string key)
    {
        if (_tables.TryGetValue(Lang, out var t) && t.TryGetValue(key, out var v)) return v;
        if (_tables["en"].TryGetValue(key, out var en)) return en;
        return key;
    }

    public void SetLang(string code)
    {
        if (!_tables.ContainsKey(code) || code == Lang) return;
        Lang = code;
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(Binding.IndexerName));
    }

    private static readonly Dictionary<string, Dictionary<string, string>> _tables = new()
    {
        ["en"] = new()
        {
            ["subtitle"] = "Build VAM model & prop assets from .glb — no Unity required",
            ["settings"] = "Settings", ["pref_prefix"] = "Package name prefix", ["pref_output"] = "Default output folder",
            ["pref_persist"] = "Saved automatically and remembered next time.",
            ["pref_nav"] = "View navigation (mouse buttons)", ["nav_btn_left"] = "Left", ["nav_btn_mid"] = "Middle", ["nav_btn_right"] = "Right",
            ["nav_orbit"] = "Orbit", ["nav_pan"] = "Pan", ["nav_zoom"] = "Zoom", ["nav_hint"] = "Wheel always zooms · F = fit to view",
            ["too_big"] = "{0} is {1} MB. Too large for live preview; baking may still work.",
            ["drop_glb"] = "Drag .glb files or a folder here",
            ["drop_hint"] = "glTF binary (.glb)",
            ["add_files"] = "Add files",
            ["add_folder"] = "Add folder",
            ["clear"] = "Clear",
            ["save_project"] = "Save project", ["open_project"] = "Open / recent projects",
            ["no_recent"] = "(no saved projects yet)", ["open_from_file"] = "Open from file…",
            ["proj_saved"] = "Project saved", ["proj_loaded"] = "Project loaded",
            ["proj_empty"] = "Nothing to save — add models first", ["proj_missing"] = "missing",
            ["queue_n"] = "{0} model(s)",
            ["mode_quick"] = "Quick",
            ["mode_advanced"] = "Advanced",
            ["package_name"] = "Package name",
            ["save_to"] = "Save to",
            ["browse"] = "Browse",
            ["target_height"] = "Target height (m)",
            ["normalize_height"] = "Normalize to height (m)",
            ["yaw"] = "Rotation",
            ["position"] = "Position offset (m) — person stays at 0,0,0",
            ["anim_clip"] = "Preview clip — all clips are packed (switchable in VAM)",
            ["pingpong"] = "Seamless loop (ping-pong)",
            ["pingpong_hint"] = "Play forward then reverse so the end meets the start — no snap-back flash. Doubles the clip length.",
            ["vcolor"] = "Use vertex colors (unlit)",
            ["vcolor_hint"] = "This model's color lives in vertex colors, which Standard ignores (renders gray). Bakes an unlit vertex-color shader instead — best for baked / cel-style models.",
            ["vcolor_auto"] = "Looks like a vertex-colored model (no textures) — auto-enabled “Use vertex colors”. If that's wrong, turn it off in Advanced.",
            ["pack_one"] = "1 model → 1 CUA package",
            ["pack_many"] = "{0} models → 1 CUA package · ~{1}",
            ["pack_separate"] = "{0} models → {0} separate CUAs (batch)",
            ["pack_toggle"] = "Pack into one CUA",
            ["pack_hint"] = "Tick to pack several models into one CUA. Disabled for multi-clip models — they convert as their own switchable bundle.",
            ["front_facing"] = "Front-facing (flip 180°)",
            ["show_ref"] = "Show person reference",
            ["adv_title"] = "Advanced editing",
            ["adv_materials"] = "Materials",
            ["adv_textures"] = "Texture slimming",
            ["adv_anim"] = "Animation",
            ["adv_doublesided"] = "Double-sided candidates",
            ["adv_hint"] = "Settings below apply to the selected model and are saved with your project.",
            ["sec_opacity"] = "Transparency",
            ["force_opaque"] = "Force all materials opaque (try auto-fix)",
            ["force_opaque_hint"] = "Many glbs mark solid surfaces transparent by mistake. Turn this on if solid parts look see-through; then fine-tune per material if needed.",
            ["risk_hint"] = "⚠ This model has transparent materials that may be mislabeled. If solid surfaces look see-through, switch to Advanced and try \"Force opaque\" before exporting.",
            ["mat_mode"] = "Rendering mode", ["mat_color"] = "Base color", ["mat_metallic"] = "Metallic",
            ["mat_smoothness"] = "Smoothness", ["mat_cutoff"] = "Alpha cutoff", ["mat_emission"] = "Emission",
            ["mat_normal"] = "Normal strength", ["mat_twosided"] = "Two-sided", ["mat_reset"] = "Reset", ["mat_intensity"] = "Intensity",
            ["collider"] = "Collider (physics)",
            ["collider_hint"] = "None for most props. Box is cheap. Convex/Mesh add real physics cost — use only when shape collision matters.",
            ["collider_warn"] = "⚠ Mesh collider ≈ {0:N0} triangles. This can heavily hurt VAM physics performance. Box is far cheaper — use Mesh only for small / low-poly props.",
            ["tex_quality"] = "Texture slimming (smaller .var)", ["tex_target"] = "Max size",
            ["tex_slim_normal"] = "Normal maps", ["tex_slim_spec"] = "Metallic / Specular maps", ["tex_slim_albedo"] = "Albedo (advanced)",
            ["tex_albedo_hint"] = "Albedo with transparency affects cutout/fade edges — only slim opaque albedo for distant props.",
            ["open_when_done"] = "Open output folder when done",
            ["convert_btn"] = "Convert to CUA",
            ["convert_all_btn"] = "Convert all ({0})",
            ["converting"] = "Converting…",
            ["ready"] = "Ready",
            ["preview_hint"] = "Select a model to preview",
            ["err_no_glb"] = "Add some .glb files first.",
            ["err_no_out"] = "Choose where to save.",
            ["err_engine"] = "Engine not found — check config.json (python / glb2cuaScript / engineExe).",
            ["done_n"] = "Done — {0} of {1} converted",
            ["hud_none"] = "—",
        },
        ["ko"] = new()
        {
            ["subtitle"] = ".glb로 VAM 모델·소품 에셋 제작 — Unity 불필요",
            ["settings"] = "설정", ["pref_prefix"] = "패키지 이름 접두사", ["pref_output"] = "기본 출력 폴더",
            ["pref_persist"] = "자동 저장되어 다음에도 유지됩니다.",
            ["pref_nav"] = "시점 조작 (마우스 버튼)", ["nav_btn_left"] = "왼쪽", ["nav_btn_mid"] = "가운데", ["nav_btn_right"] = "오른쪽",
            ["nav_orbit"] = "회전", ["nav_pan"] = "이동", ["nav_zoom"] = "확대/축소", ["nav_hint"] = "휠은 항상 확대/축소 · F = 화면 맞춤",
            ["too_big"] = "{0} 은(는) {1} MB 입니다. 실시간 미리보기에는 너무 큽니다. 베이크는 시도해 볼 수 있습니다.",
            ["drop_glb"] = ".glb 파일이나 폴더를 여기로 끌어다 놓으세요",
            ["drop_hint"] = "glTF 바이너리 (.glb)",
            ["add_files"] = "파일 추가",
            ["add_folder"] = "폴더 추가",
            ["clear"] = "지우기",
            ["save_project"] = "프로젝트 저장", ["open_project"] = "열기 / 최근 프로젝트",
            ["no_recent"] = "(저장된 프로젝트 없음)", ["open_from_file"] = "파일에서 열기…",
            ["proj_saved"] = "프로젝트 저장됨", ["proj_loaded"] = "프로젝트 불러옴",
            ["proj_empty"] = "저장할 것이 없습니다 — 먼저 모델을 추가하세요", ["proj_missing"] = "누락",
            ["queue_n"] = "모델 {0}개",
            ["mode_quick"] = "간편",
            ["mode_advanced"] = "고급",
            ["package_name"] = "패키지 이름",
            ["save_to"] = "저장 위치",
            ["browse"] = "찾아보기",
            ["target_height"] = "목표 높이 (m)",
            ["normalize_height"] = "높이로 정규화 (m)",
            ["yaw"] = "회전",
            ["position"] = "위치 오프셋 (m) — 인물은 0,0,0 고정",
            ["anim_clip"] = "미리보기 클립 — 모든 클립이 포함됨 (VAM에서 전환)",
            ["pingpong"] = "심리스 루프 (핑퐁)",
            ["pingpong_hint"] = "정방향 후 역방향 재생으로 끝과 시작이 이어져 튐이 없습니다. 클립 길이는 2배가 됩니다.",
            ["vcolor"] = "버텍스 컬러 사용 (언릿)",
            ["vcolor_hint"] = "이 모델의 색은 버텍스 컬러에 있는데 Standard는 이를 무시합니다(회색). 대신 언릿 버텍스 컬러 셰이더로 굽습니다 — 베이크/셀풍 모델에 적합.",
            ["vcolor_auto"] = "버텍스 컬러 모델로 보입니다(텍스처 없음) — ‘버텍스 컬러 사용’을 자동으로 켰습니다. 틀렸다면 고급에서 끄세요.",
            ["pack_one"] = "모델 1개 → CUA 패키지 1개",
            ["pack_many"] = "모델 {0}개 → CUA 패키지 1개 · ~{1}",
            ["pack_separate"] = "모델 {0}개 → 개별 CUA {0}개 (일괄)",
            ["pack_toggle"] = "하나의 CUA로 패킹",
            ["pack_hint"] = "여러 모델을 하나의 CUA로 패킹. 멀티클립 모델은 자체 전환형 번들로 변환되어 비활성화됩니다.",
            ["front_facing"] = "정면 보기 (180° 회전)",
            ["show_ref"] = "인물 기준 표시",
            ["adv_title"] = "고급 편집",
            ["adv_materials"] = "재질",
            ["adv_textures"] = "텍스처 경량화",
            ["adv_anim"] = "애니메이션",
            ["adv_doublesided"] = "양면 후보",
            ["adv_hint"] = "아래 설정은 선택한 모델에 적용되며 프로젝트와 함께 저장됩니다.",
            ["sec_opacity"] = "투명도",
            ["force_opaque"] = "모든 재질 강제 불투명 (자동 수정 시도)",
            ["force_opaque_hint"] = "많은 glb가 솔리드 표면을 실수로 투명 처리합니다. 솔리드 부분이 비쳐 보이면 켜고, 필요하면 재질별로 미세 조정하세요.",
            ["risk_hint"] = "⚠ 이 모델에는 잘못 표시되었을 수 있는 투명 재질이 있습니다. 솔리드 표면이 비쳐 보이면 고급 모드로 전환해 내보내기 전에 \"강제 불투명\"을 시도하세요.",
            ["mat_mode"] = "렌더링 모드", ["mat_color"] = "베이스 색상", ["mat_metallic"] = "메탈릭",
            ["mat_smoothness"] = "매끄러움", ["mat_cutoff"] = "알파 컷오프", ["mat_emission"] = "발광",
            ["mat_normal"] = "노멀 강도", ["mat_twosided"] = "양면", ["mat_reset"] = "초기화", ["mat_intensity"] = "강도",
            ["collider"] = "콜라이더 (물리)",
            ["collider_hint"] = "대부분의 소품은 None. Box는 가볍습니다. Convex/Mesh는 물리 비용이 큽니다 — 형태 충돌이 필요할 때만 사용하세요.",
            ["collider_warn"] = "⚠ 메시 콜라이더 ≈ {0:N0} 삼각형. VAM 물리 성능을 크게 저하시킬 수 있습니다. Box가 훨씬 가볍습니다 — 작거나 로우폴리 소품에만 Mesh를 사용하세요.",
            ["tex_quality"] = "텍스처 경량화 (.var 축소)", ["tex_target"] = "최대 크기",
            ["tex_slim_normal"] = "노멀 맵", ["tex_slim_spec"] = "메탈릭 / 스페큘러 맵", ["tex_slim_albedo"] = "알베도 (고급)",
            ["tex_albedo_hint"] = "투명도가 있는 알베도는 컷아웃/페이드 가장자리에 영향 — 원경용 불투명 알베도만 경량화하세요.",
            ["open_when_done"] = "완료 후 폴더 열기",
            ["convert_btn"] = "CUA로 변환",
            ["convert_all_btn"] = "전체 변환 ({0})",
            ["converting"] = "변환 중…",
            ["ready"] = "준비됨",
            ["preview_hint"] = "미리 볼 모델을 선택하세요",
            ["err_no_glb"] = "먼저 .glb 파일을 추가하세요.",
            ["err_no_out"] = "저장 위치를 선택하세요.",
            ["err_engine"] = "엔진을 찾을 수 없습니다 — config.json 확인.",
            ["done_n"] = "완료 — {1}개 중 {0}개 변환됨",
            ["hud_none"] = "—",
        },
        ["ja"] = new()
        {
            ["subtitle"] = ".glb から VAM モデル・小道具アセットを作成 — Unity 不要",
            ["settings"] = "設定", ["pref_prefix"] = "パッケージ名の接頭辞", ["pref_output"] = "既定の出力フォルダ",
            ["pref_persist"] = "自動保存され、次回も記憶されます。",
            ["pref_nav"] = "視点操作 (マウスボタン)", ["nav_btn_left"] = "左", ["nav_btn_mid"] = "中", ["nav_btn_right"] = "右",
            ["nav_orbit"] = "回転", ["nav_pan"] = "平行移動", ["nav_zoom"] = "ズーム", ["nav_hint"] = "ホイールは常にズーム · F = 全体表示",
            ["too_big"] = "{0} は {1} MB です。ライブプレビューには大きすぎます。ベイクは試せます。",
            ["drop_glb"] = ".glb ファイルかフォルダをここにドラッグ",
            ["drop_hint"] = "glTF バイナリ (.glb)",
            ["add_files"] = "ファイルを追加",
            ["add_folder"] = "フォルダを追加",
            ["clear"] = "クリア",
            ["save_project"] = "プロジェクトを保存", ["open_project"] = "開く / 最近のプロジェクト",
            ["no_recent"] = "(保存済みプロジェクトなし)", ["open_from_file"] = "ファイルから開く…",
            ["proj_saved"] = "プロジェクトを保存しました", ["proj_loaded"] = "プロジェクトを読み込みました",
            ["proj_empty"] = "保存する項目がありません — 先にモデルを追加", ["proj_missing"] = "欠落",
            ["queue_n"] = "{0} モデル",
            ["mode_quick"] = "かんたん",
            ["mode_advanced"] = "詳細",
            ["package_name"] = "パッケージ名",
            ["save_to"] = "保存先",
            ["browse"] = "参照",
            ["target_height"] = "目標の高さ (m)",
            ["normalize_height"] = "高さに正規化 (m)",
            ["yaw"] = "回転",
            ["position"] = "位置オフセット (m) — 人物は 0,0,0 固定",
            ["anim_clip"] = "プレビュークリップ — 全クリップを格納 (VAM で切替)",
            ["pingpong"] = "シームレスループ（ピンポン）",
            ["pingpong_hint"] = "順再生のあと逆再生で末尾と先頭がつながり、戻りの飛びがなくなります。クリップ長は2倍になります。",
            ["vcolor"] = "頂点カラーを使用（アンリット）",
            ["vcolor_hint"] = "このモデルの色は頂点カラーにあり、Standard はこれを無視します（グレー表示）。代わりにアンリット頂点カラーシェーダーで焼き込みます — ベイク/セル調モデル向け。",
            ["vcolor_auto"] = "頂点カラーモデルのようです（テクスチャなし）—「頂点カラーを使用」を自動でオンにしました。違う場合は詳細でオフに。",
            ["pack_one"] = "1 モデル → 1 CUA パッケージ",
            ["pack_many"] = "{0} モデル → 1 CUA パッケージ · ~{1}",
            ["pack_separate"] = "{0} モデル → 個別 CUA {0} 個（一括）",
            ["pack_toggle"] = "1つの CUA にまとめる",
            ["pack_hint"] = "複数モデルを1つのCUAにまとめる。マルチクリップのモデルは独自の切替バンドルになるため無効。",
            ["front_facing"] = "正面向き (180°回転)",
            ["show_ref"] = "人物リファレンス表示",
            ["adv_title"] = "詳細編集",
            ["adv_materials"] = "マテリアル",
            ["adv_textures"] = "テクスチャ軽量化",
            ["adv_anim"] = "アニメーション",
            ["adv_doublesided"] = "両面の候補",
            ["adv_hint"] = "下記の設定は選択中のモデルに適用され、プロジェクトと共に保存されます。",
            ["sec_opacity"] = "透明度",
            ["force_opaque"] = "全マテリアルを強制的に不透明（自動修正を試す）",
            ["force_opaque_hint"] = "多くの glb はソリッドな面を誤って透明にしています。ソリッド部分が透けて見える場合はオンにし、必要ならマテリアルごとに微調整してください。",
            ["risk_hint"] = "⚠ このモデルには誤表示の可能性がある透明マテリアルがあります。ソリッド面が透けて見える場合は、詳細モードに切り替えてエクスポート前に「強制的に不透明」を試してください。",
            ["mat_mode"] = "レンダリングモード", ["mat_color"] = "ベースカラー", ["mat_metallic"] = "メタリック",
            ["mat_smoothness"] = "滑らかさ", ["mat_cutoff"] = "アルファカットオフ", ["mat_emission"] = "エミッション",
            ["mat_normal"] = "ノーマル強度", ["mat_twosided"] = "両面", ["mat_reset"] = "リセット", ["mat_intensity"] = "強度",
            ["collider"] = "コライダー (物理)",
            ["collider_hint"] = "多くの小道具は None。Box は軽量。Convex/Mesh は物理負荷が大きい — 形状の衝突が必要な場合のみ使用。",
            ["collider_warn"] = "⚠ メッシュコライダー ≈ {0:N0} 三角形。VAM の物理性能を大きく損なう可能性があります。Box の方がはるかに軽量 — 小さい/ローポリの小道具のみ Mesh を使用。",
            ["tex_quality"] = "テクスチャ軽量化（.var 縮小）", ["tex_target"] = "最大サイズ",
            ["tex_slim_normal"] = "ノーマルマップ", ["tex_slim_spec"] = "メタリック / スペキュラマップ", ["tex_slim_albedo"] = "アルベド（詳細）",
            ["tex_albedo_hint"] = "透明度のあるアルベドはカットアウト/フェードの輪郭に影響 — 遠景用の不透明アルベドのみ軽量化を。",
            ["open_when_done"] = "完了後にフォルダを開く",
            ["convert_btn"] = "CUA に変換",
            ["convert_all_btn"] = "すべて変換 ({0})",
            ["converting"] = "変換中…",
            ["ready"] = "準備完了",
            ["preview_hint"] = "プレビューするモデルを選択",
            ["err_no_glb"] = "先に .glb ファイルを追加してください。",
            ["err_no_out"] = "保存先を選択してください。",
            ["err_engine"] = "エンジンが見つかりません — config.json を確認。",
            ["done_n"] = "完了 — {1} 件中 {0} 件を変換",
            ["hud_none"] = "—",
        },
        ["zh-Hant"] = new()
        {
            ["subtitle"] = "從 .glb 製作 VAM 模型與道具資產 — 無需 Unity",
            ["settings"] = "設定", ["pref_prefix"] = "套件名稱前綴", ["pref_output"] = "預設輸出資料夾",
            ["pref_persist"] = "自動儲存，下次會記住。",
            ["pref_nav"] = "視角操作 (滑鼠按鍵)", ["nav_btn_left"] = "左鍵", ["nav_btn_mid"] = "中鍵", ["nav_btn_right"] = "右鍵",
            ["nav_orbit"] = "旋轉", ["nav_pan"] = "平移", ["nav_zoom"] = "縮放", ["nav_hint"] = "滾輪一律縮放 · F = 適合視窗",
            ["too_big"] = "{0} 為 {1} MB，太大無法即時預覽；仍可嘗試烘焙。",
            ["drop_glb"] = "將 .glb 檔案或資料夾拖曳到此處",
            ["drop_hint"] = "glTF 二進位 (.glb)",
            ["add_files"] = "加入檔案",
            ["add_folder"] = "加入資料夾",
            ["clear"] = "清除",
            ["save_project"] = "儲存專案", ["open_project"] = "開啟 / 最近專案",
            ["no_recent"] = "(尚無已儲存專案)", ["open_from_file"] = "從檔案開啟…",
            ["proj_saved"] = "專案已儲存", ["proj_loaded"] = "專案已載入",
            ["proj_empty"] = "沒有可儲存的內容 — 請先加入模型", ["proj_missing"] = "遺失",
            ["queue_n"] = "{0} 個模型",
            ["mode_quick"] = "快捷",
            ["mode_advanced"] = "進階",
            ["package_name"] = "套件名稱",
            ["save_to"] = "儲存至",
            ["browse"] = "瀏覽",
            ["target_height"] = "目標高度 (公尺)",
            ["normalize_height"] = "正規化到高度 (公尺)",
            ["yaw"] = "旋轉",
            ["position"] = "位置偏移 (公尺) — 人物固定於 0,0,0",
            ["anim_clip"] = "預覽片段 — 全部片段都會打包 (VAM 中切換)",
            ["pingpong"] = "無縫循環（乒乓）",
            ["pingpong_hint"] = "正放後倒放，讓尾接回首、無閃回。片段長度加倍。",
            ["vcolor"] = "使用頂點色（無光照）",
            ["vcolor_hint"] = "此模型的顏色在頂點色裡，Standard 會忽略（顯示為灰）。改用無光照頂點色 shader 烘焙 — 適合烘焙/卡通風模型。",
            ["vcolor_auto"] = "看起來是頂點色模型（無貼圖）——已自動啟用「使用頂點色」。若有誤，請到進階關閉。",
            ["pack_one"] = "1 個模型 → 1 個 CUA 套件",
            ["pack_many"] = "{0} 個模型 → 1 個 CUA 套件 · ~{1}",
            ["pack_separate"] = "{0} 個模型 → {0} 個獨立 CUA（批次）",
            ["pack_toggle"] = "打包成一個 CUA",
            ["pack_hint"] = "勾選可將多個模型打包成一個 CUA。多片段模型停用（它們會轉換成各自的可切換套件）。",
            ["front_facing"] = "正面朝向 (翻轉 180°)",
            ["show_ref"] = "顯示人物參考",
            ["adv_title"] = "進階編輯",
            ["adv_materials"] = "材質",
            ["adv_textures"] = "貼圖瘦身",
            ["adv_anim"] = "動畫",
            ["adv_doublesided"] = "雙面候選",
            ["adv_hint"] = "以下設定套用於目前選取的模型，並隨專案一併儲存。",
            ["sec_opacity"] = "透明度",
            ["force_opaque"] = "強制所有材質不透明（嘗試自動修復）",
            ["force_opaque_hint"] = "許多 glb 會把實心表面誤標為透明。若實心部分看起來透明，開啟此項；必要時再逐材質微調。",
            ["risk_hint"] = "⚠ 此模型含有可能誤標的透明材質。若實心表面看起來透明，請切到進階模式，匯出前先試試「強制不透明」。",
            ["mat_mode"] = "渲染模式", ["mat_color"] = "基礎顏色", ["mat_metallic"] = "金屬度",
            ["mat_smoothness"] = "光澤度", ["mat_cutoff"] = "Alpha 裁切", ["mat_emission"] = "自發光",
            ["mat_normal"] = "法線強度", ["mat_twosided"] = "雙面", ["mat_reset"] = "重設", ["mat_intensity"] = "強度",
            ["collider"] = "碰撞體 (物理)",
            ["collider_hint"] = "多數道具用 None。Box 很輕量。Convex/Mesh 物理開銷大 — 僅在需要形狀碰撞時使用。",
            ["collider_warn"] = "⚠ 網格碰撞體 ≈ {0:N0} 個三角形。可能嚴重影響 VAM 物理效能。Box 輕量得多 — 僅在小型/低面數道具上使用 Mesh。",
            ["tex_quality"] = "貼圖瘦身（縮小 .var）", ["tex_target"] = "最大尺寸",
            ["tex_slim_normal"] = "法線貼圖", ["tex_slim_spec"] = "金屬 / 高光貼圖", ["tex_slim_albedo"] = "基礎色（進階）",
            ["tex_albedo_hint"] = "帶透明度的基礎色會影響鏤空/淡出邊緣 — 僅對遠景用的不透明基礎色瘦身。",
            ["open_when_done"] = "完成後開啟資料夾",
            ["convert_btn"] = "轉換為 CUA",
            ["convert_all_btn"] = "全部轉換 ({0})",
            ["converting"] = "轉換中…",
            ["ready"] = "就緒",
            ["preview_hint"] = "選擇要預覽的模型",
            ["err_no_glb"] = "請先加入 .glb 檔案。",
            ["err_no_out"] = "請選擇儲存位置。",
            ["err_engine"] = "找不到引擎 — 請檢查 config.json。",
            ["done_n"] = "完成 — {1} 個中已轉換 {0} 個",
            ["hud_none"] = "—",
        },
    };
}
